FROM python:3.7
MAINTAINER Mateusz Probachta <mateusz.probachta@gmail.com>

RUN apt update && apt install python-dev -y && \
     pip install watchdog && \
     ln -s /usr/bin/python /usr/bin/python3.7 && \
     mkdir -p /project

WORKDIR /project
ADD . /project
